apiVersion: v1
kind: Namespace
metadata:
  name: travelr
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: travelr
spec:
  ports:
    - port: 3306
      protocol: TCP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: mysql
  namespace: travelr
subsets:
  - addresses:
      - ip: 195.201.58.86
    ports:
      - port: 3306
  - addresses:
      - ip: 88.99.122.54
    ports:
      - port: 3306
  - addresses:
      - ip: 138.201.93.184
    ports:
      - port: 3306