version: "2"

services:
  dg-zero:
    image: dgraph/dgraph:latest
    volumes:
      - dgraph:/dgraph
    ports:
      - 5080:5080
      - 6080:6080
    restart: on-failure
    command: dgraph zero --my=dg-zero:5080
  dg-server:
    image: dgraph/dgraph:latest
    volumes:
      - dgraph:/dgraph
    ports:
      - 8080:8080
      - 9080:9080
    restart: on-failure
    command: dgraph server --my=dg-server:7080 --memory_mb=2048 --zero=dg-zero:5080
  dg-ratel:
    image: dgraph/dgraph:latest
    volumes:
      - dgraph:/dgraph
    ports:
      - 8000:8000
    command: dgraph-ratel

  gateway:
    build: gateway
    volumes:
      - ./gateway:/go/src/gateway
    working_dir: /go/src/gateway
    ports:
      - 8081:80
    links:
      - auth
      - hotels
      - rooms
      - bookings
  hotel_gateway:
    build: hotel_gateway
    volumes:
      - ./hotel_gateway:/go/src/hotel_gateway
    working_dir: /go/src/hotel_gateway
    ports:
      - 8082:80
    links:
      - rooms
    environment:
      - TRAVELR_DB_HOST=172.17.0.1:3306
      - TRAVELR_DB_USER=root
      - TRAVELR_DB_PASS=wHUgN89srLyXRTXbwDctc3k7xoxqmBW7
      - TRAVELR_DB_NAME=travelr_hotel_gateway
#  management:
#    build: management
#    volumes:
#      - ./management:/go/src/management
#    working_dir: /go/src/management
#    ports:
#      - 3002:80
#    links:
#      - auth
  auth:
    build:
      context: .
      dockerfile: Dockerfile.auth
    volumes:
      - ./auth:/go/src/auth
    working_dir: /go/src/auth
    expose:
      - 80
    environment:
      - TRAVELR_DB_HOST=dg-server:9080
  hotels:
    build:
      context: .
      dockerfile: Dockerfile.hotels
    volumes:
      - ./hotels:/go/src/hotels
    working_dir: /go/src/hotels
    links:
      - bookings
    expose:
      - 80
    environment:
      - TRAVELR_DB_HOST=dg-server:9080
  rooms:
    build: rooms
    volumes:
      - ./rooms:/go/src/rooms
    working_dir: /go/src/rooms
    links:
      - bookings
    expose:
      - 80
    environment:
      - TRAVELR_DB_HOST=172.17.0.1:3306
      - TRAVELR_DB_USER=root
      - TRAVELR_DB_PASS=wHUgN89srLyXRTXbwDctc3k7xoxqmBW7
      - TRAVELR_DB_NAME=travelr_rooms
  bookings:
    build: bookings
    volumes:
      - ./bookings:/go/src/bookings
    working_dir: /go/src/bookings
    expose:
      - 80
    environment:
      - TRAVELR_DB_HOST=dg-server:9080

volumes:
  dgraph:
