FROM golang:1.10-alpine
RUN apk --no-cache add git

RUN go get -v -d github.com/gorilla/mux
RUN go get -v -d github.com/spf13/viper

COPY ./ /go/src/github.com/fluidmediaproductions/central_hotel_door_server
WORKDIR /go/src/github.com/fluidmediaproductions/central_hotel_door_server/hotel_mqtt_auth

RUN go get -v -d
RUN CGO_ENABLED=0 go build -o hotel_mqtt_auth

FROM scratch

COPY --from=0 /go/src/github.com/fluidmediaproductions/central_hotel_door_server/hotel_mqtt_auth/hotel_mqtt_auth /hotel_mqtt_auth

ENTRYPOINT ["/hotel_mqtt_auth"]