version: "2"

services:
  gateway:
    image: golang:1.10-alpine
    volumes:
      - ./gateway:/go/src/gateway
    working_dir: /go/src/gateway
    command: sh -c "go build -o gateway *.go && ./gateway"
    ports:
      - 8080:80
    links:
      - auth
      - hotels
      - rooms
      - bookings
  hotel_gateway:
    build: .
    volumes:
      - ./hotel_gateway:/go/src/hotel_gateway
    working_dir: /go/src/hotel_gateway
    command: sh -c "go build -o hotel_gateway *.go && ./hotel_gateway"
    ports:
      - 8081:80
    links:
      - rooms
  auth:
    build: .
    volumes:
      - ./auth:/go/src/auth
    working_dir: /go/src/auth
    expose:
      - 80
    command: sh -c "go build -o auth *.go && ./auth"
  hotels:
    build: .
    volumes:
      - ./hotels:/go/src/hotels
    working_dir: /go/src/hotels
    links:
      - bookings
    expose:
      - 80
    command: sh -c "go build -o hotels *.go && ./hotels"
  rooms:
    build: .
    volumes:
      - ./rooms:/go/src/rooms
    working_dir: /go/src/rooms
    links:
      - bookings
    expose:
      - 80
    command: sh -c "go build -o rooms *.go && ./rooms"
  bookings:
    build: .
    volumes:
      - ./bookings:/go/src/bookings
    working_dir: /go/src/bookings
    expose:
      - 80
    command: sh -c "go build -o bookings *.go && ./bookings"
