FROM golang:1.10-alpine
RUN apk --no-cache add git

RUN mkdir -p /go/src/rooms
WORKDIR /go/src/rooms

COPY rooms /go/src/rooms
RUN go get -v -d
RUN CGO_ENABLED=0 go build -o rooms

FROM scratch

COPY --from=0 /go/src/rooms/rooms /rooms

ENTRYPOINT ["/rooms"]