version: "2"

services:
  gateway:
    image: golang:1.10-alpine
    volumes:
      - ./gateway:/go/src/gateway
    working_dir: /go/src/gateway
    command: sh -c "go build -o gateway && ./gateway"
    ports:
      - 8080:80
    links:
      - auth
      - hotels
      - rooms
      - bookings
  hotel_gateway:
    build: .
    volumes:
      - ./hotel_gateway:/go/src/hotel_gateway
    working_dir: /go/src/hotel_gateway
    command: sh -c "go build -o hotel_gateway && ./hotel_gateway"
    ports:
      - 8081:80
    links:
      - rooms
    environment:
      - TRAVELR_DB_HOST=172.17.0.1
      - TRAVELR_DB_USER=root
      - TRAVELR_DB_PASS=wHUgN89srLyXRTXbwDctc3k7xoxqmBW7
      - TRAVELR_DB_NAME=travelr_hotel_gateway
  auth:
    build: .
    volumes:
      - ./auth:/go/src/auth
    working_dir: /go/src/auth
    expose:
      - 80
    command: sh -c "go build -o auth && ./auth"
    environment:
      - TRAVELR_DB_HOST=172.17.0.1
      - TRAVELR_DB_USER=root
      - TRAVELR_DB_PASS=wHUgN89srLyXRTXbwDctc3k7xoxqmBW7
      - TRAVELR_DB_NAME=travelr_auth
  hotels:
    build: .
    volumes:
      - ./hotels:/go/src/hotels
    working_dir: /go/src/hotels
    links:
      - bookings
    expose:
      - 80
    command: sh -c "go build -o hotels && ./hotels"
    environment:
      - TRAVELR_DB_HOST=172.17.0.1
      - TRAVELR_DB_USER=root
      - TRAVELR_DB_PASS=wHUgN89srLyXRTXbwDctc3k7xoxqmBW7
      - TRAVELR_DB_NAME=travelr_hotels
  rooms:
    build: .
    volumes:
      - ./rooms:/go/src/rooms
    working_dir: /go/src/rooms
    links:
      - bookings
    expose:
      - 80
    command: sh -c "go build -o rooms && ./rooms"
    environment:
      - TRAVELR_DB_HOST=172.17.0.1
      - TRAVELR_DB_USER=root
      - TRAVELR_DB_PASS=wHUgN89srLyXRTXbwDctc3k7xoxqmBW7
      - TRAVELR_DB_NAME=travelr_rooms
  bookings:
    build: .
    volumes:
      - ./bookings:/go/src/bookings
    working_dir: /go/src/bookings
    expose:
      - 80
    command: sh -c "go build -o bookings && ./bookings"
    environment:
      - TRAVELR_DB_HOST=172.17.0.1
      - TRAVELR_DB_USER=root
      - TRAVELR_DB_PASS=wHUgN89srLyXRTXbwDctc3k7xoxqmBW7
      - TRAVELR_DB_NAME=travelr_bookings
