// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hotel_comms/hotel_comms.proto

/*
Package hotel_comms is a generated protocol buffer package.

It is generated from these files:
	hotel_comms/hotel_comms.proto

It has these top-level messages:
	ProtoMsg
	HotelPing
	HotelPingResp
	Door
	GetDoors
	GetDoorsResp
	Action
	GetActions
	GetActionsResp
	ActionComplete
	ActionCompleteResp
*/
package hotel_comms

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MsgType int32

const (
	MsgType_HOTEL_PING           MsgType = 0
	MsgType_HOTEL_PING_RESP      MsgType = 1
	MsgType_GET_ACTIONS          MsgType = 2
	MsgType_GET_ACTIONS_RESP     MsgType = 3
	MsgType_GET_DOORS            MsgType = 4
	MsgType_GET_DOORS_RESP       MsgType = 5
	MsgType_ACTION_COMPLETE      MsgType = 6
	MsgType_ACTION_COMPLETE_RESP MsgType = 7
)

var MsgType_name = map[int32]string{
	0: "HOTEL_PING",
	1: "HOTEL_PING_RESP",
	2: "GET_ACTIONS",
	3: "GET_ACTIONS_RESP",
	4: "GET_DOORS",
	5: "GET_DOORS_RESP",
	6: "ACTION_COMPLETE",
	7: "ACTION_COMPLETE_RESP",
}
var MsgType_value = map[string]int32{
	"HOTEL_PING":           0,
	"HOTEL_PING_RESP":      1,
	"GET_ACTIONS":          2,
	"GET_ACTIONS_RESP":     3,
	"GET_DOORS":            4,
	"GET_DOORS_RESP":       5,
	"ACTION_COMPLETE":      6,
	"ACTION_COMPLETE_RESP": 7,
}

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}
func (x MsgType) String() string {
	return proto.EnumName(MsgType_name, int32(x))
}
func (x *MsgType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MsgType_value, data, "MsgType")
	if err != nil {
		return err
	}
	*x = MsgType(value)
	return nil
}
func (MsgType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ActionType int32

const (
	ActionType_ROOM_UNLOCK ActionType = 0
)

var ActionType_name = map[int32]string{
	0: "ROOM_UNLOCK",
}
var ActionType_value = map[string]int32{
	"ROOM_UNLOCK": 0,
}

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}
func (x ActionType) String() string {
	return proto.EnumName(ActionType_name, int32(x))
}
func (x *ActionType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ActionType_value, data, "ActionType")
	if err != nil {
		return err
	}
	*x = ActionType(value)
	return nil
}
func (ActionType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ProtoMsg struct {
	Type             *MsgType `protobuf:"varint,1,req,name=type,enum=hotel_comms.MsgType" json:"type,omitempty"`
	Msg              []byte   `protobuf:"bytes,2,req,name=msg" json:"msg,omitempty"`
	UUID             *string  `protobuf:"bytes,3,req,name=UUID,json=uUID" json:"UUID,omitempty"`
	Sig              []byte   `protobuf:"bytes,4,req,name=sig" json:"sig,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ProtoMsg) Reset()                    { *m = ProtoMsg{} }
func (m *ProtoMsg) String() string            { return proto.CompactTextString(m) }
func (*ProtoMsg) ProtoMessage()               {}
func (*ProtoMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ProtoMsg) GetType() MsgType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return MsgType_HOTEL_PING
}

func (m *ProtoMsg) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *ProtoMsg) GetUUID() string {
	if m != nil && m.UUID != nil {
		return *m.UUID
	}
	return ""
}

func (m *ProtoMsg) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

type HotelPing struct {
	Timestamp        *int64 `protobuf:"varint,1,req,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *HotelPing) Reset()                    { *m = HotelPing{} }
func (m *HotelPing) String() string            { return proto.CompactTextString(m) }
func (*HotelPing) ProtoMessage()               {}
func (*HotelPing) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HotelPing) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type HotelPingResp struct {
	Success          *bool   `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	Error            *string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	ActionRequired   *bool   `protobuf:"varint,3,opt,name=actionRequired" json:"actionRequired,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HotelPingResp) Reset()                    { *m = HotelPingResp{} }
func (m *HotelPingResp) String() string            { return proto.CompactTextString(m) }
func (*HotelPingResp) ProtoMessage()               {}
func (*HotelPingResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *HotelPingResp) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func (m *HotelPingResp) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func (m *HotelPingResp) GetActionRequired() bool {
	if m != nil && m.ActionRequired != nil {
		return *m.ActionRequired
	}
	return false
}

type Door struct {
	Id               *int64  `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Door) Reset()                    { *m = Door{} }
func (m *Door) String() string            { return proto.CompactTextString(m) }
func (*Door) ProtoMessage()               {}
func (*Door) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Door) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Door) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type GetDoors struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetDoors) Reset()                    { *m = GetDoors{} }
func (m *GetDoors) String() string            { return proto.CompactTextString(m) }
func (*GetDoors) ProtoMessage()               {}
func (*GetDoors) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type GetDoorsResp struct {
	Doors            []*Door `protobuf:"bytes,1,rep,name=doors" json:"doors,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetDoorsResp) Reset()                    { *m = GetDoorsResp{} }
func (m *GetDoorsResp) String() string            { return proto.CompactTextString(m) }
func (*GetDoorsResp) ProtoMessage()               {}
func (*GetDoorsResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetDoorsResp) GetDoors() []*Door {
	if m != nil {
		return m.Doors
	}
	return nil
}

type Action struct {
	Type             *ActionType `protobuf:"varint,1,req,name=type,enum=hotel_comms.ActionType" json:"type,omitempty"`
	Id               *string     `protobuf:"bytes,2,req,name=id" json:"id,omitempty"`
	Payload          []byte      `protobuf:"bytes,3,opt,name=payload" json:"payload,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *Action) Reset()                    { *m = Action{} }
func (m *Action) String() string            { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()               {}
func (*Action) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Action) GetType() ActionType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ActionType_ROOM_UNLOCK
}

func (m *Action) GetId() string {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return ""
}

func (m *Action) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type GetActions struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetActions) Reset()                    { *m = GetActions{} }
func (m *GetActions) String() string            { return proto.CompactTextString(m) }
func (*GetActions) ProtoMessage()               {}
func (*GetActions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type GetActionsResp struct {
	Actions          []*Action `protobuf:"bytes,1,rep,name=actions" json:"actions,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *GetActionsResp) Reset()                    { *m = GetActionsResp{} }
func (m *GetActionsResp) String() string            { return proto.CompactTextString(m) }
func (*GetActionsResp) ProtoMessage()               {}
func (*GetActionsResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetActionsResp) GetActions() []*Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

type ActionComplete struct {
	ActionId         *string     `protobuf:"bytes,1,req,name=actionId" json:"actionId,omitempty"`
	ActionType       *ActionType `protobuf:"varint,2,req,name=actionType,enum=hotel_comms.ActionType" json:"actionType,omitempty"`
	Success          *bool       `protobuf:"varint,3,req,name=success" json:"success,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *ActionComplete) Reset()                    { *m = ActionComplete{} }
func (m *ActionComplete) String() string            { return proto.CompactTextString(m) }
func (*ActionComplete) ProtoMessage()               {}
func (*ActionComplete) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ActionComplete) GetActionId() string {
	if m != nil && m.ActionId != nil {
		return *m.ActionId
	}
	return ""
}

func (m *ActionComplete) GetActionType() ActionType {
	if m != nil && m.ActionType != nil {
		return *m.ActionType
	}
	return ActionType_ROOM_UNLOCK
}

func (m *ActionComplete) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

type ActionCompleteResp struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *ActionCompleteResp) Reset()                    { *m = ActionCompleteResp{} }
func (m *ActionCompleteResp) String() string            { return proto.CompactTextString(m) }
func (*ActionCompleteResp) ProtoMessage()               {}
func (*ActionCompleteResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func init() {
	proto.RegisterType((*ProtoMsg)(nil), "hotel_comms.ProtoMsg")
	proto.RegisterType((*HotelPing)(nil), "hotel_comms.HotelPing")
	proto.RegisterType((*HotelPingResp)(nil), "hotel_comms.HotelPingResp")
	proto.RegisterType((*Door)(nil), "hotel_comms.Door")
	proto.RegisterType((*GetDoors)(nil), "hotel_comms.GetDoors")
	proto.RegisterType((*GetDoorsResp)(nil), "hotel_comms.GetDoorsResp")
	proto.RegisterType((*Action)(nil), "hotel_comms.Action")
	proto.RegisterType((*GetActions)(nil), "hotel_comms.GetActions")
	proto.RegisterType((*GetActionsResp)(nil), "hotel_comms.GetActionsResp")
	proto.RegisterType((*ActionComplete)(nil), "hotel_comms.ActionComplete")
	proto.RegisterType((*ActionCompleteResp)(nil), "hotel_comms.ActionCompleteResp")
	proto.RegisterEnum("hotel_comms.MsgType", MsgType_name, MsgType_value)
	proto.RegisterEnum("hotel_comms.ActionType", ActionType_name, ActionType_value)
}

func init() { proto.RegisterFile("hotel_comms/hotel_comms.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 511 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x92, 0x4f, 0x6f, 0xda, 0x4c,
	0x10, 0xc6, 0xe3, 0x3f, 0x04, 0x3c, 0x10, 0xc7, 0xef, 0x04, 0xe9, 0x5d, 0x55, 0x8d, 0x64, 0xed,
	0xa1, 0x75, 0xa9, 0x9a, 0x4a, 0xb9, 0xe4, 0x58, 0x45, 0x80, 0x08, 0x2a, 0x60, 0xb4, 0xc0, 0xd9,
	0xb2, 0x60, 0xe5, 0x5a, 0xc2, 0xac, 0xeb, 0x35, 0x07, 0x4e, 0xfd, 0x38, 0xfd, 0x9a, 0xd5, 0x7a,
	0x03, 0x98, 0xa8, 0xea, 0x6d, 0x9e, 0xc7, 0xbf, 0x9d, 0x7d, 0x66, 0xd6, 0x70, 0xff, 0x43, 0x94,
	0x7c, 0x1b, 0xad, 0x45, 0x96, 0xc9, 0xaf, 0xb5, 0xfa, 0x21, 0x2f, 0x44, 0x29, 0xb0, 0x5d, 0xb3,
	0xe8, 0x16, 0x5a, 0x73, 0xe5, 0x4e, 0x65, 0x82, 0x01, 0xd8, 0xe5, 0x21, 0xe7, 0xc4, 0xf0, 0xcd,
	0xc0, 0x7d, 0xec, 0x3e, 0xd4, 0x8f, 0x4e, 0x65, 0xb2, 0x3c, 0xe4, 0x9c, 0x55, 0x04, 0x7a, 0x60,
	0x65, 0x32, 0x21, 0xa6, 0x6f, 0x06, 0x1d, 0xa6, 0x4a, 0x44, 0xb0, 0x57, 0xab, 0xf1, 0x80, 0x58,
	0xbe, 0x19, 0x38, 0xcc, 0xde, 0xaf, 0xc6, 0x03, 0x45, 0xc9, 0x34, 0x21, 0xb6, 0xa6, 0x64, 0x9a,
	0xd0, 0x4f, 0xe0, 0xbc, 0xa8, 0xa6, 0xf3, 0x74, 0x97, 0xe0, 0x7b, 0x70, 0xca, 0x34, 0xe3, 0xb2,
	0x8c, 0xb3, 0xbc, 0xba, 0xd3, 0x62, 0x67, 0x83, 0x26, 0x70, 0x73, 0x42, 0x19, 0x97, 0x39, 0x12,
	0x68, 0xca, 0xfd, 0x7a, 0xcd, 0xa5, 0xac, 0xe0, 0x16, 0x3b, 0x4a, 0xec, 0x42, 0x83, 0x17, 0x85,
	0x28, 0x88, 0xe9, 0x1b, 0x81, 0xc3, 0xb4, 0xc0, 0x0f, 0xe0, 0xc6, 0xeb, 0x32, 0x15, 0x3b, 0xc6,
	0x7f, 0xee, 0xd3, 0x82, 0x6f, 0x88, 0xe5, 0x1b, 0x41, 0x8b, 0xbd, 0x71, 0x69, 0x0f, 0xec, 0x81,
	0x10, 0x05, 0xba, 0x60, 0xa6, 0x9b, 0xd7, 0x1c, 0x66, 0xba, 0x51, 0x13, 0xed, 0xe2, 0x8c, 0x57,
	0x43, 0x3a, 0xac, 0xaa, 0x29, 0x40, 0x6b, 0xc4, 0x4b, 0x85, 0x4b, 0xfa, 0x04, 0x9d, 0x63, 0x5d,
	0xe5, 0xfb, 0x08, 0x8d, 0x8d, 0x12, 0xc4, 0xf0, 0xad, 0xa0, 0xfd, 0xf8, 0xdf, 0xc5, 0xfa, 0x14,
	0xc6, 0xf4, 0x77, 0x1a, 0xc1, 0xf5, 0x73, 0x15, 0x01, 0x3f, 0x5f, 0x2c, 0xfc, 0xff, 0x8b, 0x13,
	0x1a, 0xa9, 0xed, 0x5c, 0xe7, 0xd3, 0x69, 0x54, 0x3e, 0x02, 0xcd, 0x3c, 0x3e, 0x6c, 0x45, 0xac,
	0x07, 0xeb, 0xb0, 0xa3, 0xa4, 0x1d, 0x80, 0x11, 0x2f, 0x75, 0x03, 0x49, 0xbf, 0x81, 0x7b, 0x56,
	0x55, 0xd2, 0x2f, 0xd0, 0xd4, 0x3b, 0x38, 0x66, 0xbd, 0xfb, 0xcb, 0xcd, 0xec, 0xc8, 0xd0, 0x5f,
	0xe0, 0x6a, 0xab, 0x2f, 0xb2, 0x7c, 0xcb, 0x4b, 0x8e, 0xef, 0xa0, 0xa5, 0x3f, 0x8e, 0xf5, 0xc2,
	0x1c, 0x76, 0xd2, 0xf8, 0x04, 0x10, 0x9f, 0xa2, 0x57, 0x71, 0xff, 0x31, 0x59, 0x0d, 0xad, 0xbf,
	0xaf, 0x75, 0xf1, 0xbe, 0xb4, 0x0b, 0x78, 0x19, 0x40, 0x4d, 0xd1, 0xfb, 0x6d, 0x40, 0xf3, 0xf5,
	0xaf, 0x44, 0x17, 0xe0, 0x25, 0x5c, 0x0e, 0x27, 0xd1, 0x7c, 0x3c, 0x1b, 0x79, 0x57, 0x78, 0x07,
	0xb7, 0x67, 0x1d, 0xb1, 0xe1, 0x62, 0xee, 0x19, 0x78, 0x0b, 0xed, 0xd1, 0x70, 0x19, 0x3d, 0xf7,
	0x97, 0xe3, 0x70, 0xb6, 0xf0, 0x4c, 0xec, 0x82, 0x57, 0x33, 0x34, 0x66, 0xe1, 0x0d, 0x38, 0xca,
	0x1d, 0x84, 0x21, 0x5b, 0x78, 0x36, 0x22, 0xb8, 0x27, 0xa9, 0x91, 0x86, 0x6a, 0xaf, 0x0f, 0x45,
	0xfd, 0x70, 0x3a, 0x9f, 0x0c, 0x97, 0x43, 0xef, 0x1a, 0x09, 0x74, 0xdf, 0x98, 0x1a, 0x6f, 0xf6,
	0xee, 0x01, 0xce, 0x33, 0xab, 0x18, 0x2c, 0x0c, 0xa7, 0xd1, 0x6a, 0x36, 0x09, 0xfb, 0xdf, 0xbd,
	0xab, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe7, 0xa4, 0xe0, 0xaa, 0xaf, 0x03, 0x00, 0x00,
}
