// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hotel_comms/hotel_comms.proto

/*
Package hotel_comms is a generated protocol buffer package.

It is generated from these files:
	hotel_comms/hotel_comms.proto

It has these top-level messages:
	ProtoMsg
	HotelPing
	HotelPingResp
	Action
	GetActions
	GetActionsResp
*/
package hotel_comms

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MsgType int32

const (
	MsgType_HOTEL_PING       MsgType = 0
	MsgType_HOTEL_PING_RESP  MsgType = 1
	MsgType_GET_ACTIONS      MsgType = 2
	MsgType_GET_ACTIONS_RESP MsgType = 3
)

var MsgType_name = map[int32]string{
	0: "HOTEL_PING",
	1: "HOTEL_PING_RESP",
	2: "GET_ACTIONS",
	3: "GET_ACTIONS_RESP",
}
var MsgType_value = map[string]int32{
	"HOTEL_PING":       0,
	"HOTEL_PING_RESP":  1,
	"GET_ACTIONS":      2,
	"GET_ACTIONS_RESP": 3,
}

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}
func (x MsgType) String() string {
	return proto.EnumName(MsgType_name, int32(x))
}
func (x *MsgType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MsgType_value, data, "MsgType")
	if err != nil {
		return err
	}
	*x = MsgType(value)
	return nil
}
func (MsgType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ActionType int32

const (
	ActionType_ROOM_UNLOCK ActionType = 0
)

var ActionType_name = map[int32]string{
	0: "ROOM_UNLOCK",
}
var ActionType_value = map[string]int32{
	"ROOM_UNLOCK": 0,
}

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}
func (x ActionType) String() string {
	return proto.EnumName(ActionType_name, int32(x))
}
func (x *ActionType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ActionType_value, data, "ActionType")
	if err != nil {
		return err
	}
	*x = ActionType(value)
	return nil
}
func (ActionType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ProtoMsg struct {
	Type             *MsgType `protobuf:"varint,1,req,name=type,enum=hotel_comms.MsgType" json:"type,omitempty"`
	Msg              []byte   `protobuf:"bytes,2,req,name=msg" json:"msg,omitempty"`
	UUID             *string  `protobuf:"bytes,3,req,name=UUID,json=uUID" json:"UUID,omitempty"`
	Sig              []byte   `protobuf:"bytes,4,req,name=sig" json:"sig,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ProtoMsg) Reset()                    { *m = ProtoMsg{} }
func (m *ProtoMsg) String() string            { return proto.CompactTextString(m) }
func (*ProtoMsg) ProtoMessage()               {}
func (*ProtoMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ProtoMsg) GetType() MsgType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return MsgType_HOTEL_PING
}

func (m *ProtoMsg) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *ProtoMsg) GetUUID() string {
	if m != nil && m.UUID != nil {
		return *m.UUID
	}
	return ""
}

func (m *ProtoMsg) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

type HotelPing struct {
	Timestamp        *int64 `protobuf:"varint,1,req,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *HotelPing) Reset()                    { *m = HotelPing{} }
func (m *HotelPing) String() string            { return proto.CompactTextString(m) }
func (*HotelPing) ProtoMessage()               {}
func (*HotelPing) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HotelPing) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type HotelPingResp struct {
	Success          *bool   `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	Error            *string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	ActionRequired   *bool   `protobuf:"varint,3,opt,name=actionRequired" json:"actionRequired,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HotelPingResp) Reset()                    { *m = HotelPingResp{} }
func (m *HotelPingResp) String() string            { return proto.CompactTextString(m) }
func (*HotelPingResp) ProtoMessage()               {}
func (*HotelPingResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *HotelPingResp) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func (m *HotelPingResp) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func (m *HotelPingResp) GetActionRequired() bool {
	if m != nil && m.ActionRequired != nil {
		return *m.ActionRequired
	}
	return false
}

type Action struct {
	Type             *ActionType `protobuf:"varint,1,req,name=type,enum=hotel_comms.ActionType" json:"type,omitempty"`
	Id               *int64      `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	Payload          []byte      `protobuf:"bytes,3,opt,name=payload" json:"payload,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *Action) Reset()                    { *m = Action{} }
func (m *Action) String() string            { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()               {}
func (*Action) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Action) GetType() ActionType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ActionType_ROOM_UNLOCK
}

func (m *Action) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Action) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type GetActions struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetActions) Reset()                    { *m = GetActions{} }
func (m *GetActions) String() string            { return proto.CompactTextString(m) }
func (*GetActions) ProtoMessage()               {}
func (*GetActions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type GetActionsResp struct {
	Actions          []*Action `protobuf:"bytes,1,rep,name=actions" json:"actions,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *GetActionsResp) Reset()                    { *m = GetActionsResp{} }
func (m *GetActionsResp) String() string            { return proto.CompactTextString(m) }
func (*GetActionsResp) ProtoMessage()               {}
func (*GetActionsResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetActionsResp) GetActions() []*Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

func init() {
	proto.RegisterType((*ProtoMsg)(nil), "hotel_comms.ProtoMsg")
	proto.RegisterType((*HotelPing)(nil), "hotel_comms.HotelPing")
	proto.RegisterType((*HotelPingResp)(nil), "hotel_comms.HotelPingResp")
	proto.RegisterType((*Action)(nil), "hotel_comms.Action")
	proto.RegisterType((*GetActions)(nil), "hotel_comms.GetActions")
	proto.RegisterType((*GetActionsResp)(nil), "hotel_comms.GetActionsResp")
	proto.RegisterEnum("hotel_comms.MsgType", MsgType_name, MsgType_value)
	proto.RegisterEnum("hotel_comms.ActionType", ActionType_name, ActionType_value)
}

func init() { proto.RegisterFile("hotel_comms/hotel_comms.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 369 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xcf, 0x6e, 0xb2, 0x40,
	0x14, 0xc5, 0x65, 0xe0, 0xfb, 0x94, 0xab, 0x45, 0x32, 0x9a, 0x94, 0x45, 0x4d, 0x08, 0x8b, 0x86,
	0xda, 0xd4, 0x26, 0xbe, 0x40, 0x63, 0xd4, 0x28, 0xa9, 0x0a, 0x19, 0x61, 0x4d, 0x08, 0x4e, 0xe8,
	0x24, 0x22, 0x94, 0xc1, 0x85, 0x6f, 0xdf, 0x00, 0xb5, 0x60, 0xd3, 0xdd, 0x9c, 0x93, 0xdf, 0xfd,
	0x73, 0xee, 0xc0, 0xe8, 0x23, 0xc9, 0xe9, 0xd1, 0x0f, 0x93, 0x38, 0xe6, 0xaf, 0x8d, 0xf7, 0x24,
	0xcd, 0x92, 0x3c, 0xc1, 0xdd, 0x86, 0x65, 0x1c, 0xa1, 0xe3, 0x14, 0xee, 0x96, 0x47, 0xd8, 0x04,
	0x29, 0xbf, 0xa4, 0x54, 0x13, 0x74, 0x64, 0x2a, 0xd3, 0xe1, 0xa4, 0x59, 0xba, 0xe5, 0x91, 0x7b,
	0x49, 0x29, 0x29, 0x09, 0xac, 0x82, 0x18, 0xf3, 0x48, 0x43, 0x3a, 0x32, 0x7b, 0xa4, 0x78, 0x62,
	0x0c, 0x92, 0xe7, 0x59, 0x0b, 0x4d, 0xd4, 0x91, 0x29, 0x13, 0xe9, 0xec, 0x59, 0x8b, 0x82, 0xe2,
	0x2c, 0xd2, 0xa4, 0x8a, 0xe2, 0x2c, 0x32, 0x9e, 0x40, 0x5e, 0x17, 0x4d, 0x1d, 0x76, 0x8a, 0xf0,
	0x03, 0xc8, 0x39, 0x8b, 0x29, 0xcf, 0x83, 0x38, 0x2d, 0x67, 0x8a, 0xa4, 0x36, 0x8c, 0x08, 0xee,
	0x7e, 0x50, 0x42, 0x79, 0x8a, 0x35, 0x68, 0xf3, 0x73, 0x18, 0x52, 0xce, 0x4b, 0xb8, 0x43, 0xae,
	0x12, 0x0f, 0xe1, 0x1f, 0xcd, 0xb2, 0x24, 0xd3, 0x90, 0x2e, 0x98, 0x32, 0xa9, 0x04, 0x7e, 0x04,
	0x25, 0x08, 0x73, 0x96, 0x9c, 0x08, 0xfd, 0x3c, 0xb3, 0x8c, 0x1e, 0x34, 0x51, 0x17, 0xcc, 0x0e,
	0xf9, 0xe5, 0x1a, 0x3e, 0xfc, 0x9f, 0x95, 0x0e, 0x7e, 0xbe, 0xc9, 0x7f, 0x7f, 0x93, 0xbf, 0x42,
	0x1a, 0x27, 0x50, 0x00, 0xb1, 0x43, 0x79, 0x01, 0x91, 0x20, 0x76, 0x28, 0xd6, 0x4b, 0x83, 0xcb,
	0x31, 0x09, 0xaa, 0x39, 0x3d, 0x72, 0x95, 0x46, 0x0f, 0x60, 0x45, 0xf3, 0xaa, 0x01, 0x37, 0xde,
	0x40, 0xa9, 0x55, 0x19, 0xec, 0x05, 0xda, 0xd5, 0x4a, 0x45, 0x30, 0xd1, 0xec, 0x4e, 0x07, 0x7f,
	0x4c, 0x26, 0x57, 0x66, 0xec, 0x41, 0xfb, 0xfb, 0x33, 0xb0, 0x02, 0xb0, 0xb6, 0xdd, 0xe5, 0xc6,
	0x77, 0xac, 0xdd, 0x4a, 0x6d, 0xe1, 0x01, 0xf4, 0x6b, 0xed, 0x93, 0xe5, 0xde, 0x51, 0x05, 0xdc,
	0x87, 0xee, 0x6a, 0xe9, 0xfa, 0xb3, 0xb9, 0x6b, 0xd9, 0xbb, 0xbd, 0x8a, 0xf0, 0x10, 0xd4, 0x86,
	0x51, 0x61, 0xe2, 0x78, 0x04, 0x50, 0x67, 0x2c, 0x8a, 0x88, 0x6d, 0x6f, 0x7d, 0x6f, 0xb7, 0xb1,
	0xe7, 0xef, 0x6a, 0xeb, 0x2b, 0x00, 0x00, 0xff, 0xff, 0xf0, 0xfe, 0xfa, 0x25, 0x54, 0x02, 0x00,
	0x00,
}
