// Code generated by protoc-gen-go. DO NOT EDIT.
// source: hotel_comms/hotel_comms.proto

/*
Package hotel_comms is a generated protocol buffer package.

It is generated from these files:
	hotel_comms/hotel_comms.proto

It has these top-level messages:
	ProtoMsg
	HotelPing
	HotelPingResp
	Door
	GetDoors
	GetDoorsResp
	Action
	GetActions
	GetActionsResp
*/
package hotel_comms

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MsgType int32

const (
	MsgType_HOTEL_PING       MsgType = 0
	MsgType_HOTEL_PING_RESP  MsgType = 1
	MsgType_GET_ACTIONS      MsgType = 2
	MsgType_GET_ACTIONS_RESP MsgType = 3
	MsgType_GET_DOORS        MsgType = 4
	MsgType_GET_DOORS_RESP   MsgType = 5
)

var MsgType_name = map[int32]string{
	0: "HOTEL_PING",
	1: "HOTEL_PING_RESP",
	2: "GET_ACTIONS",
	3: "GET_ACTIONS_RESP",
	4: "GET_DOORS",
	5: "GET_DOORS_RESP",
}
var MsgType_value = map[string]int32{
	"HOTEL_PING":       0,
	"HOTEL_PING_RESP":  1,
	"GET_ACTIONS":      2,
	"GET_ACTIONS_RESP": 3,
	"GET_DOORS":        4,
	"GET_DOORS_RESP":   5,
}

func (x MsgType) Enum() *MsgType {
	p := new(MsgType)
	*p = x
	return p
}
func (x MsgType) String() string {
	return proto.EnumName(MsgType_name, int32(x))
}
func (x *MsgType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(MsgType_value, data, "MsgType")
	if err != nil {
		return err
	}
	*x = MsgType(value)
	return nil
}
func (MsgType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ActionType int32

const (
	ActionType_ROOM_UNLOCK ActionType = 0
)

var ActionType_name = map[int32]string{
	0: "ROOM_UNLOCK",
}
var ActionType_value = map[string]int32{
	"ROOM_UNLOCK": 0,
}

func (x ActionType) Enum() *ActionType {
	p := new(ActionType)
	*p = x
	return p
}
func (x ActionType) String() string {
	return proto.EnumName(ActionType_name, int32(x))
}
func (x *ActionType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ActionType_value, data, "ActionType")
	if err != nil {
		return err
	}
	*x = ActionType(value)
	return nil
}
func (ActionType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type ProtoMsg struct {
	Type             *MsgType `protobuf:"varint,1,req,name=type,enum=hotel_comms.MsgType" json:"type,omitempty"`
	Msg              []byte   `protobuf:"bytes,2,req,name=msg" json:"msg,omitempty"`
	UUID             *string  `protobuf:"bytes,3,req,name=UUID,json=uUID" json:"UUID,omitempty"`
	Sig              []byte   `protobuf:"bytes,4,req,name=sig" json:"sig,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *ProtoMsg) Reset()                    { *m = ProtoMsg{} }
func (m *ProtoMsg) String() string            { return proto.CompactTextString(m) }
func (*ProtoMsg) ProtoMessage()               {}
func (*ProtoMsg) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ProtoMsg) GetType() MsgType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return MsgType_HOTEL_PING
}

func (m *ProtoMsg) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *ProtoMsg) GetUUID() string {
	if m != nil && m.UUID != nil {
		return *m.UUID
	}
	return ""
}

func (m *ProtoMsg) GetSig() []byte {
	if m != nil {
		return m.Sig
	}
	return nil
}

type HotelPing struct {
	Timestamp        *int64 `protobuf:"varint,1,req,name=timestamp" json:"timestamp,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *HotelPing) Reset()                    { *m = HotelPing{} }
func (m *HotelPing) String() string            { return proto.CompactTextString(m) }
func (*HotelPing) ProtoMessage()               {}
func (*HotelPing) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *HotelPing) GetTimestamp() int64 {
	if m != nil && m.Timestamp != nil {
		return *m.Timestamp
	}
	return 0
}

type HotelPingResp struct {
	Success          *bool   `protobuf:"varint,1,req,name=success" json:"success,omitempty"`
	Error            *string `protobuf:"bytes,2,opt,name=error" json:"error,omitempty"`
	ActionRequired   *bool   `protobuf:"varint,3,opt,name=actionRequired" json:"actionRequired,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *HotelPingResp) Reset()                    { *m = HotelPingResp{} }
func (m *HotelPingResp) String() string            { return proto.CompactTextString(m) }
func (*HotelPingResp) ProtoMessage()               {}
func (*HotelPingResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *HotelPingResp) GetSuccess() bool {
	if m != nil && m.Success != nil {
		return *m.Success
	}
	return false
}

func (m *HotelPingResp) GetError() string {
	if m != nil && m.Error != nil {
		return *m.Error
	}
	return ""
}

func (m *HotelPingResp) GetActionRequired() bool {
	if m != nil && m.ActionRequired != nil {
		return *m.ActionRequired
	}
	return false
}

type Door struct {
	Id               *int64  `protobuf:"varint,1,req,name=id" json:"id,omitempty"`
	Name             *string `protobuf:"bytes,2,req,name=name" json:"name,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *Door) Reset()                    { *m = Door{} }
func (m *Door) String() string            { return proto.CompactTextString(m) }
func (*Door) ProtoMessage()               {}
func (*Door) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Door) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Door) GetName() string {
	if m != nil && m.Name != nil {
		return *m.Name
	}
	return ""
}

type GetDoors struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetDoors) Reset()                    { *m = GetDoors{} }
func (m *GetDoors) String() string            { return proto.CompactTextString(m) }
func (*GetDoors) ProtoMessage()               {}
func (*GetDoors) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type GetDoorsResp struct {
	Doors            []*Door `protobuf:"bytes,1,rep,name=doors" json:"doors,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *GetDoorsResp) Reset()                    { *m = GetDoorsResp{} }
func (m *GetDoorsResp) String() string            { return proto.CompactTextString(m) }
func (*GetDoorsResp) ProtoMessage()               {}
func (*GetDoorsResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetDoorsResp) GetDoors() []*Door {
	if m != nil {
		return m.Doors
	}
	return nil
}

type Action struct {
	Type             *ActionType `protobuf:"varint,1,req,name=type,enum=hotel_comms.ActionType" json:"type,omitempty"`
	Id               *int64      `protobuf:"varint,2,req,name=id" json:"id,omitempty"`
	Payload          []byte      `protobuf:"bytes,3,opt,name=payload" json:"payload,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *Action) Reset()                    { *m = Action{} }
func (m *Action) String() string            { return proto.CompactTextString(m) }
func (*Action) ProtoMessage()               {}
func (*Action) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Action) GetType() ActionType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ActionType_ROOM_UNLOCK
}

func (m *Action) GetId() int64 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *Action) GetPayload() []byte {
	if m != nil {
		return m.Payload
	}
	return nil
}

type GetActions struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *GetActions) Reset()                    { *m = GetActions{} }
func (m *GetActions) String() string            { return proto.CompactTextString(m) }
func (*GetActions) ProtoMessage()               {}
func (*GetActions) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type GetActionsResp struct {
	Actions          []*Action `protobuf:"bytes,1,rep,name=actions" json:"actions,omitempty"`
	XXX_unrecognized []byte    `json:"-"`
}

func (m *GetActionsResp) Reset()                    { *m = GetActionsResp{} }
func (m *GetActionsResp) String() string            { return proto.CompactTextString(m) }
func (*GetActionsResp) ProtoMessage()               {}
func (*GetActionsResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *GetActionsResp) GetActions() []*Action {
	if m != nil {
		return m.Actions
	}
	return nil
}

func init() {
	proto.RegisterType((*ProtoMsg)(nil), "hotel_comms.ProtoMsg")
	proto.RegisterType((*HotelPing)(nil), "hotel_comms.HotelPing")
	proto.RegisterType((*HotelPingResp)(nil), "hotel_comms.HotelPingResp")
	proto.RegisterType((*Door)(nil), "hotel_comms.Door")
	proto.RegisterType((*GetDoors)(nil), "hotel_comms.GetDoors")
	proto.RegisterType((*GetDoorsResp)(nil), "hotel_comms.GetDoorsResp")
	proto.RegisterType((*Action)(nil), "hotel_comms.Action")
	proto.RegisterType((*GetActions)(nil), "hotel_comms.GetActions")
	proto.RegisterType((*GetActionsResp)(nil), "hotel_comms.GetActionsResp")
	proto.RegisterEnum("hotel_comms.MsgType", MsgType_name, MsgType_value)
	proto.RegisterEnum("hotel_comms.ActionType", ActionType_name, ActionType_value)
}

func init() { proto.RegisterFile("hotel_comms/hotel_comms.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 439 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x91, 0xc1, 0x6f, 0xda, 0x30,
	0x14, 0xc6, 0x8b, 0x13, 0x06, 0x79, 0xd0, 0x34, 0x7b, 0x45, 0x9a, 0x0f, 0xab, 0x14, 0xf9, 0xb0,
	0x65, 0x4c, 0xeb, 0xa4, 0x5e, 0x76, 0x9c, 0xaa, 0x82, 0x28, 0x5a, 0x21, 0xc8, 0xc0, 0x39, 0x8a,
	0xc0, 0xca, 0x22, 0x11, 0x9c, 0xc5, 0x41, 0x1a, 0xff, 0xfd, 0xe4, 0xb8, 0x81, 0x30, 0xf5, 0xf6,
	0xbe, 0x2f, 0x3f, 0xdb, 0xdf, 0xfb, 0x02, 0x77, 0xbf, 0x65, 0x29, 0x76, 0xd1, 0x46, 0x66, 0x99,
	0xfa, 0xde, 0x98, 0xef, 0xf3, 0x42, 0x96, 0x12, 0x7b, 0x0d, 0x8b, 0xed, 0xa0, 0xbb, 0xd0, 0xee,
	0x4c, 0x25, 0x18, 0x80, 0x5d, 0x1e, 0x73, 0x41, 0x5b, 0x3e, 0x09, 0xdc, 0x87, 0xc1, 0x7d, 0xf3,
	0xe8, 0x4c, 0x25, 0xab, 0x63, 0x2e, 0x78, 0x45, 0xa0, 0x07, 0x56, 0xa6, 0x12, 0x4a, 0x7c, 0x12,
	0xf4, 0xb9, 0x1e, 0x11, 0xc1, 0x5e, 0xaf, 0xa7, 0x23, 0x6a, 0xf9, 0x24, 0x70, 0xb8, 0x7d, 0x58,
	0x4f, 0x47, 0x9a, 0x52, 0x69, 0x42, 0x6d, 0x43, 0xa9, 0x34, 0x61, 0x5f, 0xc0, 0x79, 0xd6, 0x97,
	0x2e, 0xd2, 0x7d, 0x82, 0x1f, 0xc1, 0x29, 0xd3, 0x4c, 0xa8, 0x32, 0xce, 0xf2, 0xea, 0x4d, 0x8b,
	0x9f, 0x0d, 0x96, 0xc0, 0xf5, 0x09, 0xe5, 0x42, 0xe5, 0x48, 0xa1, 0xa3, 0x0e, 0x9b, 0x8d, 0x50,
	0xaa, 0x82, 0xbb, 0xbc, 0x96, 0x38, 0x80, 0xb6, 0x28, 0x0a, 0x59, 0x50, 0xe2, 0xb7, 0x02, 0x87,
	0x1b, 0x81, 0x9f, 0xc0, 0x8d, 0x37, 0x65, 0x2a, 0xf7, 0x5c, 0xfc, 0x39, 0xa4, 0x85, 0xd8, 0x52,
	0xcb, 0x6f, 0x05, 0x5d, 0xfe, 0x9f, 0xcb, 0x86, 0x60, 0x8f, 0xa4, 0x2c, 0xd0, 0x05, 0x92, 0x6e,
	0x5f, 0x73, 0x90, 0x74, 0xab, 0x37, 0xda, 0xc7, 0x99, 0xa8, 0x96, 0x74, 0x78, 0x35, 0x33, 0x80,
	0xee, 0x44, 0x94, 0x1a, 0x57, 0xec, 0x07, 0xf4, 0xeb, 0xb9, 0xca, 0xf7, 0x19, 0xda, 0x5b, 0x2d,
	0x68, 0xcb, 0xb7, 0x82, 0xde, 0xc3, 0xfb, 0x8b, 0xfa, 0x34, 0xc6, 0xcd, 0x77, 0x16, 0xc1, 0xbb,
	0xc7, 0x2a, 0x02, 0x7e, 0xbd, 0x28, 0xfc, 0xc3, 0xc5, 0x09, 0x83, 0x34, 0x3a, 0x37, 0xf9, 0xc8,
	0x29, 0x1f, 0x85, 0x4e, 0x1e, 0x1f, 0x77, 0x32, 0x36, 0x8b, 0xf5, 0x79, 0x2d, 0x59, 0x1f, 0x60,
	0x22, 0x4a, 0x73, 0x81, 0x62, 0x3f, 0xc1, 0x3d, 0xab, 0x2a, 0xe9, 0x37, 0xe8, 0x98, 0x0e, 0xea,
	0xac, 0xb7, 0x6f, 0xbc, 0xcc, 0x6b, 0x66, 0xf8, 0x17, 0x3a, 0xaf, 0x7f, 0x1f, 0x5d, 0x80, 0xe7,
	0x70, 0x35, 0x7e, 0x89, 0x16, 0xd3, 0xf9, 0xc4, 0xbb, 0xc2, 0x5b, 0xb8, 0x39, 0xeb, 0x88, 0x8f,
	0x97, 0x0b, 0xaf, 0x85, 0x37, 0xd0, 0x9b, 0x8c, 0x57, 0xd1, 0xe3, 0xd3, 0x6a, 0x1a, 0xce, 0x97,
	0x1e, 0xc1, 0x01, 0x78, 0x0d, 0xc3, 0x60, 0x16, 0x5e, 0x83, 0xa3, 0xdd, 0x51, 0x18, 0xf2, 0xa5,
	0x67, 0x23, 0x82, 0x7b, 0x92, 0x06, 0x69, 0x0f, 0xef, 0x00, 0xce, 0x35, 0xe8, 0x7b, 0x79, 0x18,
	0xce, 0xa2, 0xf5, 0xfc, 0x25, 0x7c, 0xfa, 0xe5, 0x5d, 0xfd, 0x0b, 0x00, 0x00, 0xff, 0xff, 0x8b,
	0x1d, 0x82, 0xfa, 0xe8, 0x02, 0x00, 0x00,
}
