apiVersion: v1
kind: ConfigMap
metadata:
  name: bookings-config
  namespace: travelr
data:
  dbHost: mysql
  dbUser: travelr
  dbName: travelr_bookings
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookings
  namespace: travelr
  labels:
    app: bookings
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bookings
  template:
    metadata:
      labels:
        app: bookings
    spec:
      containers:
        - name: auth
          image: evilben/travelr_bookings:(hash)
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: TRAVELR_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: bookings-config
                  key: dbHost
            - name: TRAVELR_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: bookings-config
                  key: dbUser
            - name: TRAVELR_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: bookings-config
                  key: dbName
            - name: TRAVELR_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-auth
                  key: pass
            - name: TRAVELR_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: secret
---
apiVersion: v1
kind: Service
metadata:
  name: bookings
  namespace: travelr
spec:
  selector:
    app: bookings
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
