apiVersion: v1
kind: ConfigMap
metadata:
  name: rooms-config
  namespace: travelr
data:
  dbHost: "dgraph-server-public:9080"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rooms
  namespace: travelr
  labels:
    app: rooms
spec:
  replicas: 3
  selector:
    matchLabels:
      app: rooms
  template:
    metadata:
      labels:
        app: rooms
    spec:
      containers:
        - name: auth
          image: evilben/travelr_rooms:(hash)
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: TRAVELR_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: rooms-config
                  key: dbHost
            - name: TRAVELR_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: secret
---
apiVersion: v1
kind: Service
metadata:
  name: rooms
  namespace: travelr
spec:
  selector:
    app: rooms
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
