apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotel-mqtt-auth
  namespace: travelr
  labels:
    app: hotel-mqtt-auth
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hotel-mqtt-auth
  template:
    metadata:
      labels:
        app: hotel-mqtt-auth
    spec:
      containers:
        - name: hotel-mqtt-auth
          image: evilben/travelr_hotel_mqtt_auth:(hash)
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: TRAVELR_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: secret
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-mqtt-auth
  namespace: travelr
spec:
  selector:
    app: hotel-mqtt-auth
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
