apiVersion: v1
kind: ConfigMap
metadata:
  name: hotels-config
  namespace: travelr
data:
  dbHost: "mysql:3306"
  dbUser: travelr
  dbName: travelr_hotels
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hotels
  namespace: travelr
  labels:
    app: hotels
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hotels
  template:
    metadata:
      labels:
        app: hotels
    spec:
      containers:
        - name: auth
          image: evilben/travelr_hotels:(hash)
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: TRAVELR_DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: hotels-config
                  key: dbHost
            - name: TRAVELR_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: hotels-config
                  key: dbUser
            - name: TRAVELR_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: hotels-config
                  key: dbName
            - name: TRAVELR_DB_PASS
              valueFrom:
                secretKeyRef:
                  name: db-auth
                  key: pass
            - name: TRAVELR_JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt
                  key: secret
---
apiVersion: v1
kind: Service
metadata:
  name: hotels
  namespace: travelr
spec:
  selector:
    app: hotels
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
